
apiVersion: v1
kind: Service
metadata:
  name: django-electricaa-service
spec:
  selector:
    app: django-electricaa
  ports:
    - protocol: TCP
      port: 8000          # External port
      targetPort: 8000    # Pod's container port
      nodePort: 31924     # Port exposed on each Node (only for NodePort/LoadBalancer types)
  type: NodePort
